!io
version: 0
type: xml
param_root: !list
  objects: {{}}
  lists:
    ParamSet: !list
      objects:
        1258832850: !obj
          use_rigid_body_set_num: 1
          use_ragdoll: false
          use_cloth: false
          use_support_bone: false
          use_character_controller: false
          use_contact_info: true
          use_edge_rigid_body_num: 0
          use_system_group_handler: true
      lists:
        RigidContactInfo: !list
          objects:
            3387849585: !obj {{contact_point_info_num: 1, collision_info_num: 1}}
            ContactPointInfo_0: !obj {{name: !str32 Body, type: !str32 Body, num: 64}}
            CollisionInfo_0: !obj {{name: !str32 Body, type: !str32 Body}}
          lists: {{}}
        RigidBodySet: !list
          objects: {{}}
          lists:
            RigidBodySet_0: !list
              objects:
                4288596824: !obj {{set_name: !str32 Body, type: !str32 from_shape_type, num: {0}}}
              lists:
{1}
